# Generated by Django 5.1.3 on 2024-11-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
